### ISSUE TITLE
Chapter 2 Section 2 Maze Solving

### ISSUE THREAD

**Issue by sbauer322** [sbauer322/ccsp#10]
- [x] Linear and Binary Search from Chapter 2 Section 1 #9
- [x] Maze Generation #11
- [x] Depth First Search #12
- [x] Breadth First Search #13 
- [x] A* Search #14

**Comment by sbauer322** [comment]
All sections code complete
